version: '4.0'

actions:
  generate_dataset:
    run: ehrql:v1 generate-dataset analysis/dataset_definition.py --output output/dataset.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset.csv.gz

  measures:
    run: ehrql:v1 generate-measures analysis/measures.py --output output/measures/measures.csv
    outputs:
      moderately_sensitive:
        dataset: output/measures/measures.csv

  table:
    run: r:latest analysis/process/pop_characteristics.R
    needs: [generate_dataset]
    outputs:
      moderately_sensitive:
        table1: output/processed/table.csv
        table2: output/processed/table_pfu.csv

  time_series:
    run: r:latest analysis/process/measures_process.R
    needs: [measures]
    outputs:
      moderately_sensitive:
        timeseries: output/processed/time_series.csv
