version: '5.0'

actions:
  # generate_dataset_explore:
  #   run: ehrql:v1 generate-dataset analysis/dataset_definition_explore.py --output output/dataset_explore.csv.gz
  #   outputs:
  #     highly_sensitive:
  #       dataset: output/dataset_explore.csv.gz

  # table_explore:
  #   run: r:v2 analysis/process/data_exploration.R
  #   needs: [generate_dataset_explore]
  #   outputs:
  #     moderately_sensitive:
  #       table1: output/processed/table_explore.csv
  #       #table2: output/processed/table_pfu_explore.csv
  #       table3: output/processed/counts_explore.csv

  generate_dataset_everyone:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_everyone.py --output output/dataset_everyone.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset_everyone.csv.gz

  generate_dataset_rheum:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_specialty.py --output output/dataset_rheumatology.csv.gz
      --
      --trt_func_code 410
    outputs:
      highly_sensitive:
        dataset: output/dataset_rheumatology.csv.gz
  
  generate_dataset_derm:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_specialty.py --output output/dataset_dermatology.csv.gz
      --
      --trt_func_code 330
    outputs:
      highly_sensitive:
        dataset: output/dataset_dermatology.csv.gz

  generate_dataset_gastro:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_specialty.py --output output/dataset_gastroenterology.csv.gz
      --
      --trt_func_code 301
    outputs:
      highly_sensitive:
        dataset: output/dataset_gastroenterology.csv.gz

  measures_everyone:
    run: ehrql:v1 generate-measures analysis/measures_everyone.py --output output/measures/measures_everyone.csv
    outputs:
      moderately_sensitive:
        dataset: output/measures/measures_everyone.csv
    
  measures_rheum:
    run: ehrql:v1 generate-measures analysis/measures_specialty.py --output output/measures/measures_rheum.csv
      --
      --trt_func_code 410
    outputs:
      moderately_sensitive:
        dataset: output/measures/measures_rheum.csv
  
  measures_gastro:
    run: ehrql:v1 generate-measures analysis/measures_specialty.py --output output/measures/measures_gastro.csv
      --
      --trt_func_code 301
    outputs:
      moderately_sensitive:
        dataset: output/measures/measures_gastro.csv
  
  measures_derm:
    run: ehrql:v1 generate-measures analysis/measures_specialty.py --output output/measures/measures_derm.csv
      --
      --trt_func_code 330
    outputs:
      moderately_sensitive:
        dataset: output/measures/measures_derm.csv

  measures_time_rheum:
    run: ehrql:v1 generate-measures analysis/measures_time_specialty.py --output output/measures/measures_time_rheum.csv
      --
      --trt_func_code 410
    outputs:
      moderately_sensitive:
        dataset: output/measures/measures_time_rheum.csv

  measures_time_gastro:
    run: ehrql:v1 generate-measures analysis/measures_time_specialty.py --output output/measures/measures_time_gastro.csv
      --
      --trt_func_code 301
    outputs:
      moderately_sensitive:
        dataset: output/measures/measures_time_gastro.csv

  measures_time_derm:
    run: ehrql:v1 generate-measures analysis/measures_time_specialty.py --output output/measures/measures_time_derm.csv
      --
      --trt_func_code 330
    outputs:
      moderately_sensitive:
        dataset: output/measures/measures_time_derm.csv

  # table:
  #   run: r:v2 analysis/process/pop_characteristics.R
  #   needs: [generate_dataset_everyone, generate_dataset_rheum, generate_dataset_gastro, generate_dataset_derm]
  #   outputs:
  #     moderately_sensitive:
  #       table1: output/processed/table.csv
  #       table2: output/processed/table_pfu.csv
  #       table3: output/processed/table_rheum.csv

  # time_series:
  #   run: r:v2 analysis/process/measures_process.R
  #   needs: [measures_everyone, measures_rheum, measures_gastro, measures_derm]
  #   outputs:
  #     moderately_sensitive:
  #       timeseries1: output/processed/time_series_overall.csv
  #       timeseries2: output/processed/time_series_specialty.csv

  # opa_time:
  #   run: r:v2 analysis/process/measures_time_process.R
  #   needs: [measures_time_rheum, measures_time_gastro, measure_time_derm]
  #   outputs:
  #     moderately_sensitive:
  #       table: output/processed/outpatient_time.csv