version: '4.0'

actions:
  generate_dataset_explore:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_explore.py --output output/dataset_explore.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset_explore.csv.gz

  table_explore:
    run: r:latest analysis/process/data_exploration.R
    needs: [generate_dataset_explore]
    outputs:
      moderately_sensitive:
        table1: output/processed/table_explore.csv
        #table2: output/processed/table_pfu_explore.csv
        table3: output/processed/counts_explore.csv

  generate_dataset:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_everyone.py --output output/dataset_everyone.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset_everyone.csv.gz
  
  generate_dataset_rheum:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_rheum.py --output output/dataset_rheum.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset_rheum.csv.gz

  measures:
    run: ehrql:v1 generate-measures analysis/measures.py --output output/measures/measures.csv
    outputs:
      moderately_sensitive:
        dataset: output/measures/measures.csv

  table:
    run: r:latest analysis/process/pop_characteristics.R
    needs: [generate_dataset, generate_dataset_rheum]
    outputs:
      moderately_sensitive:
        table1: output/processed/table.csv
        table2: output/processed/table_pfu.csv
        table3: output/processed/table_rheum.csv
        table4: output/processed/visits_stats.csv

  time_series:
    run: r:latest analysis/process/measures_process.R
    needs: [measures]
    outputs:
      moderately_sensitive:
        timeseries: output/processed/time_series.csv

