version: '4.0'

actions:
  generate_dataset_explore:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_explore.py --output output/dataset_explore.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset_explore.csv.gz

  table_explore:
    run: r:latest analysis/process/data_exploration.R
    needs: [generate_dataset_explore]
    outputs:
      moderately_sensitive:
        table1: output/processed/table_explore.csv
        #table2: output/processed/table_pfu_explore.csv
        table3: output/processed/counts_explore.csv

  generate_dataset:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_everyone.py --output output/dataset_everyone.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset_everyone.csv.gz
  
  generate_dataset_rheum:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_rheum.py --output output/dataset_rheum.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset_rheum.csv.gz

  measures:
    run: ehrql:v1 generate-measures analysis/measures.py --output output/measures/measures.csv
    outputs:
      moderately_sensitive:
        dataset: output/measures/measures.csv

  measures_london:
    run: ehrql:v1 generate-measures analysis/measures_region.py --output output/measures/measures_london.csv 
      -- 
      --param_region London
    outputs:
      moderately_sensitive:
        dataset: output/measures/measures_london.csv

  measures_northeast:
    run: ehrql:v1 generate-measures analysis/measures_region.py --output output/measures/measures_northeast.csv 
      -- 
      --param_region 'North East'
    outputs:
      moderately_sensitive:
        dataset: output/measures/measures_northeast.csv

  measures_northwest:
    run: ehrql:v1 generate-measures analysis/measures_region.py --output output/measures/measures_northwest.csv 
      -- 
      --param_region 'North West'
    outputs:
      moderately_sensitive:
        dataset: output/measures/measures_northwest.csv

  measures_yorkshire:
    run: ehrql:v1 generate-measures analysis/measures_region.py --output output/measures/measures_yorkshire.csv 
      --
      --param_region 'Yorkshire and The Humber'
    outputs:
      moderately_sensitive:
        dataset: output/measures/measures_yorkshire.csv

  measures_eastmidlands:
    run: ehrql:v1 generate-measures analysis/measures_region.py --output output/measures/measures_eastmidlands.csv 
      --
      --param_region 'East Midlands'
    outputs:
      moderately_sensitive:
        dataset: output/measures/measures_eastmidlands.csv

  measures_westmidlands:
    run: ehrql:v1 generate-measures analysis/measures_region.py --output output/measures/measures_westmidlands.csv 
      -- 
      --param_region 'West Midlands'
    outputs:
      moderately_sensitive:
        dataset: output/measures/measures_westmidlands.csv

  measures_east:
    run: ehrql:v1 generate-measures analysis/measures_region.py --output output/measures/measures_east.csv 
      --
      --param_region East
    outputs:
      moderately_sensitive:
        dataset: output/measures/measures_east.csv

  measures_southeast:
    run: ehrql:v1 generate-measures analysis/measures_region.py --output output/measures/measures_southeast.csv 
      --
      --param_region 'South East'
    outputs:
      moderately_sensitive:
        dataset: output/measures/measures_southeast.csv

  measures_southwest:
    run: ehrql:v1 generate-measures analysis/measures_region.py --output output/measures/measures_southwest.csv 
      --
      --param_region 'South West'
    outputs:
      moderately_sensitive:
        dataset: output/measures/measures_southwest.csv

  table:
    run: r:latest analysis/process/pop_characteristics.R
    needs: [generate_dataset, generate_dataset_rheum]
    outputs:
      moderately_sensitive:
        table1: output/processed/table.csv
        table2: output/processed/table_pfu.csv
        table3: output/processed/table_rheum.csv

  time_series:
    run: r:latest analysis/process/measures_process.R
    needs: [measures]
    outputs:
      moderately_sensitive:
        timeseries1: output/processed/time_series_overall.csv
        timeseries2: output/processed/time_series_specialty.csv
  
  time_series_region:
    run: r:latest analysis/process/measures_region_process.R
    needs: [measures_london, measures_east, measures_eastmidlands, measures_northeast, measures_northwest, measures_southeast, measures_southwest, measures_westmidlands, measures_yorkshire]
    outputs:
      moderately_sensitive:
        timeseries1: output/processed/ts_*.csv
        timeseries2: output/processed/ts_sp*.csv

  visits:
    run: r:latest analysis/process/visit_stats.R
    needs: [generate_dataset_rheum]
    outputs:
      moderately_sensitive:
        table: output/processed/visit_stats.csv